### ISSUE TITLE
Bad Discord Invite

### ISSUE THREAD

**Issue by DeathSmack** [wrkzcoin/HellBot#1]
When I hover on invite link I get this https://invite-hellbot.wrkz.work/
but when I follow link I end up at a german book store.... 

at

https://www.methodik-kg.mohrsiebeck.com/

What is that!?

**Comment by wrkzdev** [comment]
Hello,

I will fix it. It still pointed to old IP address.

**Comment by wrkzdev** [comment]
It's updated now. It should be fixed. Thank you very much.
